import React, { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '@/components/footer/footer'
import Cursor from '@/components/cursor/cursor'
import MobNav from '@/components/mobNav/mobNav'
import IntroSection from '@/sections/introSection/introSection'
import RewardSection from '@/sections/rewardSection/rewardSection'
import SocialSection from '@/sections/socialSection/socialSection'
import ExploreSection from '@/sections/exploreSection/exploreSection'

const Home: NextPage = () => {
 
  const [showNav , setShowNav] = useState<boolean>(false)

  return (
    <div className={''}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      { showNav && <MobNav showNav={showNav} setShowNav={setShowNav} /> }

       <Cursor />

       <IntroSection showNav={showNav} setShowNav={setShowNav} />

       <SocialSection />

       <RewardSection />

       <ExploreSection />

       <Footer />
       
     
    </div>
  )
}

export default Home;
