import type { NextPage } from 'next'
import Head from 'next/head'

import { nfts } from '@/mock/media.mock'

const Home: NextPage = () => {

  console.log(nfts)
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/phosphor-icons"></script>
      </Head>

     <div>
     
       <h1>Hello world</h1>
        <figure>
          <img src={nfts.sampleOne} alt="nft"/>
        </figure>
     </div>
    </div>
  )
}

export default Home
