import type { NextPage } from 'next'
import Head from 'next/head'
import Cursor from '@/components/cursor/cursor'
import IntroSection from '@/sections/introSection/introSection'
import RewardSection from '@/sections/rewardSection/rewardSection'
import { nfts } from '@/mock/media.mock'

const Home: NextPage = () => {

  return (
    <div className={''}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/phosphor-icons"></script>
      </Head>

    
       <Cursor />

       <IntroSection />

       <RewardSection />
       
     
    </div>
  )
}

export default Home
